# Generated by Django 4.0.5 on 2022-06-29 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
        ('user', '0003_mypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypage',
            name='name',
            field=models.TextField(default='User'),
        ),
        migrations.AddField(
            model_name='mypage',
            name='order_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_lists', to='order.order'),
        ),
        migrations.AddField(
            model_name='mypage',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user.review'),
        ),
    ]
