# Generated by Django 4.0.5 on 2022-06-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_mypage_name_mypage_order_list_mypage_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mypage',
        ),
    ]
