# Generated by Django 4.0.5 on 2022-06-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_joinorder_delivery_status_joinorder_money_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('COL', 'Collecting'), ('MC', 'MoneyCall'), ('ING', 'Deliverying'), ('DC', 'DeliveryCompleted'), ('FIN', 'Finish')], default='COL', max_length=3),
        ),
    ]
